### ISSUE TITLE
Mismatching colors between GUI and terminal in org-mode

### ISSUE THREAD

**Issue by AladW** [wasamasa/gotham-theme#19]
See the screenshot:

http://i.imgur.com/S8IZSp2.png

In particular, "DONE" and "PENDING" lack contrast in the terminal. 

Configuration:

emacs 24.5, org 8.2.10, GTK2 on XFCE 4.12 (init: http://git.io/vsRYb)
termite with the gotham-contrib theme mentioned in the README (config: http://git.io/vsROs)

**Comment by AladW** [comment]
describe-char on DONE (terminal):

```
             position: 45 of 6756 (1%), column: 3                               
            character: D (displayed as D) (codepoint 68, #o104, #x44)           
    preferred charset: ascii (ASCII (ISO646 IRV))                               
code point in charset: 0x44                                                     
               script: latin                                                    
               syntax: w        which means: word                               
             category: .:Base, L:Left-to-right (strong), a:ASCII, l:Latin, r:Ro\
man                                                                             
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"       
          buffer code: #x44  
```

describe-face on DONE (terminal):

```
Face: org-done (sample) (customize this face)                                   
                                                                                
Documentation:                                                                  
Face used for todo keywords that indicate DONE items.                           
                                                                                
Defined in `org-faces.el'.                                                      
                                                                                
           Family: unspecified                                                  
          Foundry: unspecified                                                  
            Width: unspecified 
```
